ENV['SWIFT_VERSION'] = '4'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target "EyepetizerApp" do
use_frameworks!

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SnapKit'
pod 'StarWars'
pod 'APESuperHUD'
pod 'JSAnimatedImagesView'
pod 'YYWebImage'

end